server:
  port: 8088
  
spring: 
  datasource:
    travelbase:
      url: jdbc:mysql://127.0.0.1:3306/travel_base?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC&useSSL=true
      username: root
      password: 123456
     
    tripmanager:
      url: jdbc:mysql://127.0.0.1:3306/trip_manager?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC&useSSL=true
      username: root
      password: 123456
